# Kopier/indsæt for offentliggørelse af hjemmeside via Terminal (Alt+Shift+M) =>
# quarto publish quarto-pub --no-prompt --no-browser

project:
  type: website
  render:
    - "*.qmd"
    - "index.qmd" # "!index.qmd"
    - "indbydelse_tilmelding.qmd" # "!indbydelse_tilmelding.qmd"
    - "præmier_deltagere.qmd" # "!præmier_deltagere.qmd"
    - "regler.qmd" # "!regler.qmd"
    - "wcpp.qmd" # "!wcpp.qmd"
    - "koncept.qmd" # "!koncept.qmd"
    - "bi.qmd" # "!bi.qmd"

website:
  # title: "DM i Ping Pong"
  title: "<small>DM i Ping Pong</small><a style=display:inline-block;background:#398FCC;color:#FFFFFF;border-style:solid;border-width:medium;border-color:#FFFFFF;text-align:center;font-weight:bold;font-size:90%;border-radius:20px;padding-left:10px;padding-right:10px;padding-top:5px;padding-bottom:5px;text-decoration:none href=indbydelse_tilmelding.qmd#tilmelding class=bi-tags-fill>&nbsp;Tilmeld</a>"
  favicon: "Filer/Ping-Pong-DK.png"
  google-analytics: "G-6903XX1GX6"
  search: true
  page-navigation: true
  navbar:
    logo: "Filer/Ping-Pong-DK.png"
    background: "#398FCC"
  sidebar:
    style: docked
    background: light
    contents:
      - section: "DM i Ping Pong {{< var var.event_år >}}"
        contents:
        - href: "indbydelse_tilmelding.qmd"
        - href: "præmier_deltagere.qmd"
      - text: "---"
      - section: "Generelt om Ping Pong"
        contents:
        - href: "regler.qmd"
        - href: "wcpp.qmd"
        - href: "koncept.qmd"
      - text: "---"
      - section: "Eksterne links"
        contents:
        - text: "<a class=bi-box-arrow-up-right href=https://www.btex.dk/sanwei-wcpp-sandpapirsbat.html target=_blank>&nbsp;Køb bat hos BTEX</a>"
        - text: "<a class=bi-box-arrow-up-right href=https://matchroom.live/sports/ping_pong target=_blank>&nbsp;Matchroom Live</a>"
        - text: "<a class=bi-box-arrow-up-right href=https://classichardbat.com/home target=_blank>&nbsp;World Ping Pong</a>"
      - text: "<br>"
      - text: |
          <a href=https://bordtennisdanmark.dk/kalender/dm-i-ping-pong target=_blank><img src=Filer/BTDK.png style=height:15px></a>
          &nbsp;<a href=https://www.dgi.dk/bordtennis target=_blank><img src=Filer/DGI.png style=height:15px></a>
          &nbsp;<a href=http://hoerningbtk.dk target=_blank><img src=Filer/Arrangør.png style=height:15px></a>
          &nbsp;<a class=bi-facebook style=color:#1877F2 href={{< var var.facebook_event_url >}} target=_blank></a>
          &nbsp;<a class=bi-messenger style=color:#0695FF href=https://m.me/{{< var var.facebook_side_id >}} target=_blank></a>
          &nbsp;<a class=bi-github style=color:#9F7BE1 href=https://github.com/bsbenja/ping_pong_dm target=_blank></a>
  page-footer:
    background: light
    left:
      - text: "<img src=Filer/Ping-Pong-DK.png style=height:15px>&nbsp;DM i Ping Pong"
    right:
      - text: |
          <a href=https://bordtennisdanmark.dk/kalender/dm-i-ping-pong target=_blank><img src=Filer/BTDK.png style=height:15px></a>
          &nbsp;<a href=https://www.dgi.dk/bordtennis target=_blank><img src=Filer/DGI.png style=height:15px></a>
          &nbsp;<a href=http://hoerningbtk.dk target=_blank><img src=Filer/Arrangør.png style=height:15px></a>
          &nbsp;<a class=bi-facebook style=color:#1877F2 href={{< var var.facebook_event_url >}} target=_blank></a>
          &nbsp;<a class=bi-messenger style=color:#0695FF href=https://m.me/{{< var var.facebook_side_id >}} target=_blank></a>
          &nbsp;<a class=bi-github style=color:#9F7BE1 href=https://github.com/bsbenja/ping_pong_dm target=_blank></a>

format:
  html:
    theme:
      light: united
    mainfont: verdana
    css: styles.css
    df-print: kable
    fontsize: "11pt"
    linkcolor: "#398FCC"
    section-title-footnotes: "Fodnoter"
    toc-title: "Indhold på side"
    fig-align: left
    toc: true
    smooth-scroll: true
    toc-location: right
    toc-depth: 6
    white-space: pre-wap
    code-overflow: wrap

editor: visual

knitr:
  opts_chunk:
    comment: ""

execute:
  eval: true
  output: true
  freeze: false
  echo: false
  warning: false
  error: false
