# Kopier/indsæt for offentliggørelse af hjemmeside via Terminal (Alt+Shift+M) =>
# quarto publish quarto-pub --no-prompt --no-browser

project:
  type: website

website:
  title: "DM i Ping Pong"
  favicon: "Filer/Ping Pong DK.png"
  google-analytics: "G-6903XX1GX6"
  page-navigation: true
  search: true
  navbar:
    logo: "Filer/Ping Pong DK.png"
    background: "#398FCC"
  sidebar:
    style: docked
    background: light
    contents:
      - section: "DM i Ping Pong 2023"
        contents:
        - href: "index.qmd"
        - href: "præmier_deltagere.qmd"
        - href: "tidsplan_indbydelse.qmd"
      - text: "---"
      - section: "Generelt om Ping Pong"
        contents:
        - href: "regler.qmd"
        - href: "wcpp.qmd"
        - href: "koncept.qmd"
      - text: "---"
      - section: "Eksterne links"
        contents:
        - text: "<a class=bi-box-arrow-up-right href=https://www.btex.dk/sanwei-wcpp-sandpapirsbat.html target=_blank>&nbsp;Køb bat hos BTEX</a>"
        - text: "<a class=bi-box-arrow-up-right href=https://matchroom.live/sports/ping_pong target=_blank>&nbsp;Matchroom Live</a>"
        - text: "<a class=bi-box-arrow-up-right href=https://bordtennisdanmark.dk/statistik/ping-pong-dm target=_blank>&nbsp;BTDK</a>"
    tools:
      - href: "https://github.com/bsbenja/ping_pong_dm"
        icon: "github"
      - href: "https://www.facebook.com/events/452302656395308"
        icon: "facebook"
      - href: "https://m.me/100183334928231"
        icon: "messenger"
  page-footer:
    background: light
    left:
      - text: "<a href=https://www.facebook.com/100183334928231 target=_blank style=text-decoration:none>Ping Pong DK</a>"
    right:
      - text: "<a class=bi-github href=https://github.com/bsbenja/ping_pong_dm target=_blank></a>"
      - text: "&emsp;<a class=bi-facebook href=https://www.facebook.com/events/452302656395308 target=_blank></a>"
      - text: "&emsp;<a class=bi-messenger href=https://m.me/100183334928231 target=_blank></a>"

format:
  html:
    theme:
      light: united
    mainfont: verdana
    css: styles.css
    df-print: kable
    fontsize: "90%"
    linkcolor: "#398FCC"
    section-title-footnotes: "Fodnoter"
    toc-title: "Indhold på side"
    toc: true
    smooth-scroll: true
    toc-location: right
    toc-depth: 6
    white-space: pre-wap
    code-overflow: wrap

editor: visual

knitr:
  opts_chunk:
    comment: ""

execute:
  eval: true
  output: true
  freeze: false
  echo: false
  warning: false
  error: false